using System;
using System.Collections.Generic;
using System.Text;

namespace Simed.Entity.Request
{
    public class FormularioRequestCliente
    {
        public string NombreRazonSocialDG { get; set; }
        public string DireccionDG { get; set; }
        public string PaisId { get; set; }
        public string CiudadPrinciaplDDG { get; set; }
        public string TelefonoFijoDG { get; set; }
        public string CelularDG { get; set; }
        public string CorreoElecontronicoDG { get; set; }
        public string DireccionFacturaDG { get; set; }
        public string CiudadFacturaDG { get; set; }
        public string DireccionPedidoDG { get; set; }
        public string CiudadPedidoDG { get; set; }
        public string DireccionPedidoSecundarioDG { get; set; }
        public string CiudadPedidoSecundarioDG { get; set; }
        public string NombreContactoAreaCobranza { get; set; }
        public string TelefonoContactoAreaCobranza { get; set; }
        public string CorreoContactoAreaCobranza { get; set; }
        public string NombreContactoAreaFinanciera { get; set; }
        public string TelefonoContactoAreaFinanciera { get; set; }
        public string CorreoContactoAreaFinanciera { get; set; }
        public string TipoIdentificacionIdIT { get; set; }
        public string CualIdentificacionIT { get; set; }
        public string NumeroIdentificacionIT { get; set; }
        public string cboTipoContribuyente { get; set; }
        public string cboTipoSociedad { get; set; }
        public string txtCualSociedadIT { get; set; }
        public string cboOrigenCapital { get; set; }
        public string cboActividadEconomica { get; set; }
        public string txtCualEconomicaIT { get; set; }
        public string txtSuperIntendenciaIT { get; set; }
        public string txtFechaConstitucionIT { get; set; }
        public string cboRegimen { get; set; }
        public string txtActividadPrincipalIAE { get; set; }
        public string txtActividadSecundariaIAE { get; set; }
        public string txtNombreRepresentanteLegalIRL { get; set; }
        public string cboTipoIdenticacionLegal { get; set; }
        public string txtNumeroIdentificacionIRL { get; set; }
        public string cboNacionalidad { get; set; }
        public string txtCualIRL { get; set; }
        public string txtFechaExpedicionDocumentoIRL { get; set; }
        public string txtDireccionResidenciaIRL { get; set; }
        public string txtCiudadIRL { get; set; }
        public string checkSiGozaPEP { get; set; }
        public string checkNoGozaPEP { get; set; }
        public string txtEspecifiqueGozaPEP { get; set; }
        public string checkSiManejaPEP { get; set; }
        public string checkNoManejaPEP { get; set; }
        public string txtEspecifiqueManejaPEP { get; set; }
        public string checkSiOcupaPEP { get; set; }
        public string checkNoOcupaPEP { get; set; }
        public string txtEspecifiqueOcupaPEP { get; set; }
        public string checkSiVinculo1PEP { get; set; }
        public string checkNoVinculo1PEP { get; set; }
        public string txtEspecifiqueVinculo1PEP { get; set; }
        public string checkSiVinculo2PEP { get; set; }
        public string checkNoVinculo2PEP { get; set; }
        public string txtEspecifiqueVinculo2PEP { get; set; }
        public string txtNombreApellidoPEP { get; set; }
        public string txtCargoPEP { get; set; }
        public string checkSiAccionistaISA { get; set; }
        public string checkNoAccionistaISA { get; set; }
        public string txtNombreApellidoAccionista1ISA { get; set; }
        public string txtTipoIdAccionista1ISA { get; set; }
        public string txtNroDocumentoAccionista1ISA { get; set; }
        public string txtParticipacionAccionista1ISA { get; set; }
        public string txtNacionalidadAccionista1ISA { get; set; }
        public string txtNombreApellidoAccionista2ISA { get; set; }
        public string txtTipoIdAccionista2ISA { get; set; }
        public string txtNroDocumentoAccionista2ISA { get; set; }
        public string txtParticipacionAccionista2ISA { get; set; }
        public string txtNacionalidadAccionista2ISA { get; set; }
        public string txtNombreApellidoAccionista3ISA { get; set; }
        public string txtTipoIdAccionista3ISA { get; set; }
        public string txtNroDocumentoAccionista3ISA { get; set; }
        public string txtParticipacionAccionista3ISA { get; set; }
        public string txtNacionalidadAccionista3ISA { get; set; }
        public string txtNombreApellidoAccionista4ISA { get; set; }
        public string txtTipoIdAccionista4ISA { get; set; }
        public string txtNroDocumentoAccionista4ISA { get; set; }
        public string txtParticipacionAccionista4ISA { get; set; }
        public string txtNacionalidadAccionista4ISA { get; set; }
        public string FechaCorte { get; set; }
        public string checkSolesIF { get; set; }
        public string checkDolaresIF { get; set; }
        public string txtActivosIF { get; set; }
        public string txtIngresosMensualesIF { get; set; }
        public string txtPasivosIF { get; set; }
        public string txtEgresosMensualesIF { get; set; }
        public string txtPatrimonioIF { get; set; }
        public string txtOtrosIngresosIF { get; set; }
        public string txtConceptoOtrosIngresosIF { get; set; }
        public string txtEmpresa1RC { get; set; }
        public string txtRuc1RC { get; set; }
        public string txtTelefono1RC { get; set; }
        public string txtDireccion1RC { get; set; }
        public string txtCiudad1RC { get; set; }
        public string txtEmpresa2RC { get; set; }
        public string txtRuc2RC { get; set; }
        public string txtTelefono2RC { get; set; }
        public string txtDireccion2RC { get; set; }
        public string txtCiudad2RC { get; set; }
        public string txtInstitucionRB { get; set; }
        public string txtNroCuentaRB { get; set; }
        public string txtTipoCuentaRB { get; set; }
        public string txtBeneficiarioRB { get; set; }
        public string txtEmpresaRB { get; set; }
        public string txtRucRB { get; set; }
        public string txtTelefonoRB { get; set; }
        public string txtDireccionRB { get; set; }
        public string cboUnidad { get; set; }
        public string cboSubUnidad { get; set; }
        public string cboAsesorComercial { get; set; }
        public string txtDescripcion { get; set; }
        public string cboTipoPago { get; set; }
        public string cuposolicitado { get; set; }
        public string txtAsesorComercialVUI { get; set; }
        public string Filename1 { get; set; }
        public string Filename2 { get; set; }
        public string Filename3 { get; set; }
        public string Filename4 { get; set; }
        public string Filename5 { get; set; }
        public string Filename6 { get; set; }
        public string Filename7 { get; set; }
        public string Filename8 { get; set; }
        public string Filename9 { get; set; }
        public string Filename10 { get; set; }
        public string Filename11 { get; set; }
        public string Filename12 { get; set; }
        public string Filename13 { get; set; }

        public string tokenCode { get; set; }
    }
}
